### ISSUE TITLE
Store data about Diary in SQLite database

### ISSUE THREAD

**Issue by divanydio** [Ora-Kool/aad-team-6-animation-challenge#20]
- [x] create contract class
- [x] implement worker class
- [x] effective store data into database
- [x]  Add DairyApplication Class to provide database helper
- [x] Load datas from database using Cursor

**Comment by divanydio** [comment]
- [ ] Add DairyApplication Class to provide database helper

**Comment by allenbangai** [comment]
I will take this isseu on... Will start working on it tomorrow evening...
My Android studio is having this issue since 7 days, I will try terminate with it today...
This is the gist link of my Issue.. You can take  a look to help... https://gist.github.com/allenbangai/71cb1c92b3d11148c8145b03ab96e1f4

**Comment by divanydio** [comment]
This issue is already done !
Choose another one in the list , i'm going to close this one .
Please do not lose your motivation . 
Sorry.
