### ISSUE TITLE
Animate the RecyclerView Scroll behavior using a third party library

### ISSUE THREAD

**Issue by BonyaO** [Ora-Kool/aad-team-6-animation-challenge#24]
I think applying the scale in animation on the recycler adapter as shown in the app will be a cool feature

**Comment by Ora-Kool** [comment]
So can you handle it?

**Comment by BonyaO** [comment]
From the course video, it's implementation is simple in kotlin. But I think
think I can read through to see the Java implementation to use it. I'm
positive about it

**Comment by 47leonel-wabo** [comment]
I've already added necessary dependency as shown at pluralsight and set an animation to recycler view, but it is not visible because instead of using **notifyDataSetChanged** we should use **notifyItemChanged(int)** "int" representing the position.
But when I look the code I didn't figure out how to get that position.
**So our peer in charge of implementing the recycler view should fix that, kindly!**

**Comment by 47leonel-wabo** [comment]
link https://android-arsenal.com/details/1/1327

**Comment by BonyaO** [comment]
Hi, on which of the branches did you add the item animators? The version of
the deploy branch I cloned did not have any of those. DO I HAVE TO CLONE
THE NEW VERSION OF DEPLOY branch to see your changes?
